#!/bin/bash

touch $HOME/.hamonikr/${0##*/}.log
echo "$(date +%Y-%m-%d_%H:%M) : ${0##*/} $1 running." | tee $HOME/.hamonikr/${0##*/}.log

# update hamonikr default logo setting
if [ -f "/home/$USER/.cinnamon/configs/menu@cinnamon.org/0.json" ] ; then
    echo "update hamonikr default logo setting" | tee -a $HOME/.hamonikr/${0##*/}.log
    sed -i 's/"value": "linuxmint-logo-ring-symbolic"/"value": "hamonikr-logo"/g' /home/$USER/.cinnamon/configs/menu@cinnamon.org/0.json
fi

if [ ! -f "/home/$USER/.hamonikr/default_dconf.done" ] ; then

    # delete cache
    if [ -d "/home/$USER/.cache" ] ; then
        echo "Deleted cache" | tee -a $HOME/.hamonikr/${0##*/}.log
        rm -rf /home/$USER/.cache/*
    fi

    # copy applet to user home
    if [ -d "/home/$USER/.cinnamon/configs" ] ; then
        echo "Copy applets" | tee -a $HOME/.hamonikr/${0##*/}.log
        cp -af /usr/share/cinnamon/applets/expo@cinnamon.org /home/$USER/.cinnamon/configs/
        cp -af /usr/share/cinnamon/applets/scale@cinnamon.org /home/$USER/.cinnamon/configs/        
        cp -af /usr/share/cinnamon/applets/user@cinnamon.org /home/$USER/.cinnamon/configs/                
        cp -af /usr/share/cinnamon/applets/xrandr@cinnamon.org /home/$USER/.cinnamon/configs/
    fi

    # Albert Launcher Settings
    if [ -d "/etc/skel/.config/albert" ] ; then
        echo "copy albert launcher setting" | tee -a $HOME/.hamonikr/${0##*/}.log
        cp -af /etc/skel/.config/albert /home/$USER/.config/
    fi                
    
    if [ ! -f "/home/$USER/.hamonikr/hamonikr-theme-backup.dconf" ] ; then
        # IF installed hamonikr-themes 

        echo "update default desktop settings" | tee -a $HOME/.hamonikr/${0##*/}.log        
        # 패널 설정
        gsettings set org.cinnamon panels-enabled "['1:0:bottom']"
        gsettings set org.cinnamon panels-height "['1:38']"
        gsettings set org.cinnamon panel-zone-icon-sizes '[{"panelId": 1, "left": 24, "center": 24, "right": 16}]'
        gsettings set org.cinnamon panel-zone-symbolic-icon-sizes '[{"panelId": 1, "left": 24, "center": 24, "right": 16}]'

        # 패널 애플릿 배치
        gsettings set org.cinnamon enabled-applets "['panel1:left:0:menu@cinnamon.org:0', 
        'panel1:left:1:grouped-window-list@cinnamon.org:1', 
        'panel1:right:0:systray@cinnamon.org:2', 
        'panel1:right:1:expo@cinnamon.org:3', 
        'panel1:right:3:notifications@cinnamon.org:5', 
        'panel1:right:4:printers@cinnamon.org:6', 
        'panel1:right:5:removable-drives@cinnamon.org:7', 
        'panel1:right:6:keyboard@cinnamon.org:8', 
        'panel1:right:7:bluetooth@cinnamon.org:9', 
        'panel1:right:8:network@cinnamon.org:10', 
        'panel1:right:9:sound@cinnamon.org:11', 
        'panel1:right:10:power@cinnamon.org:12', 
        'panel1:right:11:calendar@cinnamon.org:13', 
        'panel1:right:12:show-desktop@cinnamon.org:14', 
        'panel1:right:13:user@cinnamon.org:15'
        ]"

        # 테마 설정
        gsettings set org.cinnamon.desktop.interface icon-theme 'HamoniKR'
        gsettings set org.cinnamon.desktop.interface gtk-theme 'HamoniKR'
        gsettings set org.cinnamon.desktop.wm.preferences theme 'HamoniKR'
        gsettings set org.cinnamon.theme name 'HamoniKR'

        # 폰트 설정
        gsettings set org.cinnamon.desktop.interface font-name 'Noto Sans CJK KR 10'
        gsettings set org.nemo.desktop font 'Noto Sans CJK KR 10'        
        gsettings set org.gnome.desktop.interface document-font-name 'Noto Sans CJK KR 10'    
        gsettings set org.cinnamon.desktop.wm.preferences titlebar-font 'Noto Sans CJK KR 11'
        gsettings set org.gnome.desktop.interface monospace-font-name 'Droid Sans Mono 12'
        gsettings set org.gnome.meld custom-font 'Droid Sans Mono, 12'
        gsettings set org.x.viewer.plugins.pythonconsole use-system-font false
        gsettings set org.x.viewer.plugins.pythonconsole font 'Droid Sans Mono 9'

        # 바탕화면, greeter 배경화면
        gsettings set org.cinnamon.desktop.background picture-uri "file:////usr/share/backgrounds/hamonikr/default_background.jpg"
        gsettings set org.gnome.desktop.background picture-uri "file:////usr/share/backgrounds/hamonikr/default_background.jpg"
        gsettings set org.mate.background picture-filename "file:////usr/share/backgrounds/hamonikr/default_background.jpg"                
        gsettings set x.dm.slick-greeter background '/usr/share/backgrounds/hamonikr/default_background.jpg'

    fi

    # gnome-terminal 설정
    if [ -f "/home/$USER/.hamonikr/hamonikr-terminal.dconf" ] ; then
        echo "update default terminal settings"  | tee -a $HOME/.hamonikr/${0##*/}.log
        dconf load /org/gnome/terminal/legacy/profiles:/:`gsettings list-recursively org.gnome.Terminal.ProfilesList | grep default | cut -d' ' -f3 | tr -d "'"`/ < /home/$USER/.hamonikr/hamonikr-terminal.dconf
    fi

    # nimf 입력기 설정
    if command -v nimf &> /dev/null
    then
        echo "update default nimf settings"  | tee -a $HOME/.hamonikr/${0##*/}.log    
        im-config -n nimf
    fi

    # 단축키
    if command -v shutter &> /dev/null ; then
        if ! command -v fsearch &> /dev/null ; then
            echo "update default keyboard shortcut settings for shutter"  | tee -a $HOME/.hamonikr/${0##*/}.log        
            gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/cinnamon/desktop/keybindings/custom-keybindings/custom0/ binding "['<Primary><Shift>p']"
            gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/cinnamon/desktop/keybindings/custom-keybindings/custom0/ command 'shutter -s'
            gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/cinnamon/desktop/keybindings/custom-keybindings/custom0/ name '특정영역 화면캡처'
            gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/cinnamon/desktop/keybindings/custom-keybindings/custom1/ binding "['<Primary><Alt>p']"
            gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/cinnamon/desktop/keybindings/custom-keybindings/custom1/ command 'shutter -w'
            gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/cinnamon/desktop/keybindings/custom-keybindings/custom1/ name '선택한 윈도우 화면캡처'
            gsettings set org.cinnamon.desktop.keybindings custom-list "['custom0','custom1']"
        else
            echo "update default keyboard shortcut settings for shutter and fsearch"  | tee -a $HOME/.hamonikr/${0##*/}.log                
            gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/cinnamon/desktop/keybindings/custom-keybindings/custom0/ binding "['<Primary><ALT><Shift>p']"
            gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/cinnamon/desktop/keybindings/custom-keybindings/custom0/ command 'shutter -s'
            gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/cinnamon/desktop/keybindings/custom-keybindings/custom0/ name '특정영역 화면캡처'
            gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/cinnamon/desktop/keybindings/custom-keybindings/custom1/ binding "['<Primary><Alt>p']"
            gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/cinnamon/desktop/keybindings/custom-keybindings/custom1/ command 'shutter -w'
            gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/cinnamon/desktop/keybindings/custom-keybindings/custom1/ name '선택한 윈도우 화면캡처'
            gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/cinnamon/desktop/keybindings/custom-keybindings/custom2/ binding "['<Primary><Shift>f']"
            gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/cinnamon/desktop/keybindings/custom-keybindings/custom2/ command 'fsearch'
            gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/cinnamon/desktop/keybindings/custom-keybindings/custom2/ name '데스크탑 검색'
            gsettings set org.cinnamon.desktop.keybindings custom-list "['custom0','custom1','custom2']"
        fi
    else
        if command -v fsearch &> /dev/null ; then    
            echo "update default keyboard shortcut settings for fsearch"  | tee -a $HOME/.hamonikr/${0##*/}.log                
            gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/cinnamon/desktop/keybindings/custom-keybindings/custom0/ binding "['<Primary><Shift>f']"
            gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/cinnamon/desktop/keybindings/custom-keybindings/custom0/ command 'fsearch'
            gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/cinnamon/desktop/keybindings/custom-keybindings/custom0/ name '데스크탑 검색'
            gsettings set org.cinnamon.desktop.keybindings custom-list "['custom0']"
        fi
    fi

    # search provider
    echo "update search provider settings"  | tee -a $HOME/.hamonikr/${0##*/}.log    
    cp -a /usr/share/cinnamon/search_providers/google@hamonikr.org $HOME/.local/share/cinnamon/search_providers/google@hamonikr.org
    gsettings set org.cinnamon enabled-search-providers [\"google@hamonikr.org\"]

    echo "created settins-done file"  | tee -a $HOME/.hamonikr/${0##*/}.log        
    touch /home/$USER/.hamonikr/default_dconf.done

    # fix asbru-cm font
    if [ -f "/home/$USER/.config/asbru/asbru.yml" ] ; then
        echo "Update asbru font seting" | tee -a $HOME/.hamonikr/${0##*/}.log
        sed -i 's/Monospace/Droid Sans Mono/g' /home/$USER/.config/asbru/asbru.yml
    fi

    # figlet LOGO
    if [ -f "$HOME/.bashrc" ]; then
        # if "figlet" text in .bashrc
        if [ -z "`cat $HOME/.bashrc | grep figlet`" ]; then
            echo "Update figlet setting" | tee -a $HOME/.hamonikr/${0##*/}.log
            echo 'figlet "$HOSTNAME"' >> $HOME/.bashrc
        fi
    fi

    # Desktop Community Icon
    if [ -f "/usr/share/applications/hamonikrorg.desktop" ]; then
        echo "Update hamonikr community link icon" | tee -a $HOME/.hamonikr/${0##*/}.log
        if [ -d "$HOME/Desktop" ]; then
            cp /usr/share/applications/hamonikrorg.desktop $HOME/Desktop/hamonikrorg.desktop
        else
            cp /usr/share/applications/hamonikrorg.desktop $HOME/바탕화면/hamonikrorg.desktop
        fi
    fi
fi
