#!/bin/sh
# postinst script 
# see: dh_installdeb(1)

set -e

case "$1" in
    configure|upgrade|update|reconfigure|triggered)
        
        update-rc.d hamonikr-system defaults
        
        if which glib-compile-schemas >/dev/null 2>&1 ; then
            glib-compile-schemas /usr/share/glib-2.0/schemas
        fi

        if which update-mime-database >/dev/null 2>&1 ; then
            update-mime-database /usr/share/mime
        fi

        if which update-desktop-database >/dev/null 2>&1 ; then
            update-desktop-database /usr/share/applications
        fi

        if which update-icon-caches >/dev/null 2>&1 ; then
            update-icon-caches /usr/share/icons
        fi

        # systemd 명령어 실행 부분을 chroot 환경에서 동작하지 않도록 수정 (ISO 빌드시 오류)
        if [ -z "$FAKEROOTKEY" ] && [ -d /run/systemd/system ]; then
            if which systemctl >/dev/null 2>&1 ; then
                # if exist service
                if systemctl --all --type service | grep -q "mintsystem";then
                    if [ $(systemctl is-enabled mintsystem) = "enabled" ] ; then
                        systemctl disable mintsystem
                    fi
                fi
    
                if systemctl --all --type service | grep -q "ubuntu-system-adjustments";then
                    if [ $(systemctl is-enabled ubuntu-system-adjustments) = "enabled" ] ; then
                    systemctl disable ubuntu-system-adjustments
                    fi
                fi
    
                if systemctl --all --type service | grep -q "debian-system-adjustments";then
                    if [ $(systemctl is-enabled debian-system-adjustments) = "enabled" ] ; then
                    systemctl disable debian-system-adjustments
                    fi
                fi
                
                systemctl enable hamonikr-system.service
                systemctl daemon-reload
            fi
        fi

        /usr/lib/hamonikr/hamonikr-system/hamonikr-adjust.py

        # Source is not available in the sh shell
        [ -f /etc/lsb-release ] && . /etc/lsb-release 
        [ -f /etc/os-release ] && . /etc/os-release 

        # Apply HamoniKR OS infomation in system
        [ ! -d "/etc/hamonikr/.bak" ] && mkdir -p "/etc/hamonikr/.bak"
        [ -f /etc/issue ] && cp /etc/issue /etc/hamonikr/.bak/issue.bak
        [ -f /etc/issue.net ] && cp /etc/issue.net /etc/hamonikr/.bak/issue.net.bak
        [ -f /etc/lsb-release ] && cp /etc/lsb-release /etc/hamonikr/.bak/lsb-release.bak
        [ -f /etc/os-release ] && cp /etc/os-release /etc/hamonikr/.bak/os-release.bak

        # OS check
        if [ "X$ID_LIKE" = "Xubuntu" ] || [ "X$ID_LIKE" = "Xubuntu debian" ]; then
            echo "postinst... ubuntu"
            [ -f /etc/hamonikr/issue ] && cp -f /etc/hamonikr/issue /etc/issue
            [ -f /etc/hamonikr/issue.net ] &&  cp -f /etc/hamonikr/issue.net /etc/issue.net
            [ -f /etc/hamonikr/lsb-release ] &&  cp -f /etc/hamonikr/lsb-release /etc/lsb-release
            [ -f /etc/hamonikr/os-release ] &&  cp -f /etc/hamonikr/os-release /etc/os-release
            [ -f /etc/hamonikr/os-release ] &&  cp -f /etc/hamonikr/os-release /usr/lib/os-release
        elif [ "X$ID_LIKE" = "Xdebian" ] || [ "X$ID" = "Xdebian" ]; then
            echo "postinst... debian"
            [ -f /etc/hamonikr/issue ] && cp -f /etc/hamonikr/issue /etc/issue
            [ -f /etc/hamonikr/issue.net ] &&  cp -f /etc/hamonikr/issue.net /etc/issue.net
            [ -f /etc/hamonikr/lsb-release-debian ] &&  cp -f /etc/hamonikr/lsb-release-debian /etc/lsb-release
            [ -f /etc/hamonikr/os-release-debian ] &&  cp -f /etc/hamonikr/os-release-debian /etc/os-release
            [ -f /etc/hamonikr/os-release-debian ] &&  cp -f /etc/hamonikr/os-release-debian /usr/lib/os-release
        else
            echo "Can not detect OS code. It seems other OS."
        fi

    ;;

    abort-upgrade|abort-remove|abort-deconfigure)

    ;;
    
    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
