#!/bin/sh

set -e

case "$1" in
    remove|upgrade|deconfigure)
		update-rc.d -f hamonikr-system remove

        if which systemctl >/dev/null 2>&1
        then
            # if exist service
            if systemctl --all --type service | grep -q "mintsystem";then
                if [ $(systemctl is-enabled mintsystem) = "disabled" ] ; then
                    systemctl enable mintsystem
                fi
            fi
                       
            if systemctl --all --type service | grep -q "ubuntu-system-adjustments";then
                if [ $(systemctl is-enabled ubuntu-system-adjustments) = "disabled" ] ; then
                    systemctl enable ubuntu-system-adjustments
                fi
            fi                       

            if systemctl --all --type service | grep -q "debian-system-adjustments";then
                if [ $(systemctl is-enabled debian-system-adjustments) = "disabled" ] ; then
                    systemctl enable debian-system-adjustments
                fi
            fi      

            systemctl daemon-reload
        fi

        # Remove HamoniKR update-grub wrapper
        if [ -f /etc/hamonikr/adjustments/15-remove-update-grub-wrapper.remove ]; then
            /etc/hamonikr/adjustments/15-remove-update-grub-wrapper.remove || true
        fi

        # Apply HamoniKR OS infomation in system
        [ -f /etc/hamonikr/.bak/issue.bak ] && cp -f /etc/hamonikr/.bak/issue.bak /etc/issue
        [ -f /etc/hamonikr/.bak/issue.net.bak ] && cp -f /etc/hamonikr/.bak/issue.net.bak /etc/issue.net
        [ -f /etc/hamonikr/.bak/lsb-release.bak ] && cp -f /etc/hamonikr/.bak/lsb-release.bak /etc/lsb-release
        [ -f /etc/hamonikr/.bak/os-release.bak ] && cp -f /etc/hamonikr/.bak/os-release.bak /etc/os-release
        [ -f /etc/hamonikr/.bak/os-release.bak ] && cp -f /etc/hamonikr/.bak/os-release.bak /usr/lib/os-release

        [ -d "/etc/hamonikr/.bak" ] && rm -rf "/etc/hamonikr/.bak"
        [ -d "/etc/hamonikr/adjustments" ] && rm -rf "/etc/hamonikr/adjustments"
        ;;
    failed-upgrade)
        ;;
    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

