#!/bin/sh

set -e

case "$1" in
    remove|upgrade|deconfigure)
		update-rc.d -f hamonikr-system remove

        if which systemctl >/dev/null 2>&1
        then
            if [ $(systemctl is-enabled ubuntu-system-adjustments) = "disabled" ] ; then
                systemctl enable ubuntu-system-adjustments
            fi        
            systemctl daemon-reload
        fi

        # Apply HamoniKR OS infomation in system
        cp -f /etc/hamonikr/.bak/issue.bak /etc/issue
        cp -f /etc/hamonikr/.bak/issue.net.bak /etc/issue.net
        cp -f /etc/hamonikr/.bak/lsb-release.bak /etc/lsb-release
        cp -f /etc/hamonikr/.bak/os-release.bak /etc/os-release
        cp -f /etc/hamonikr/.bak/os-release.bak /usr/lib/os-release

        [ -d "/etc/hamonikr/.bak" ] && rm -rf "/etc/hamonikr/.bak"
        [ -d "/etc/hamonikr/adjustments" ] && rm -rf "/etc/hamonikr/adjustments"

        # remove unused files in user home
        RUID=$(who | awk 'FNR == 1 {print $1}')
        [ -f /home/${RUID}/.config/user-dirs.dirs ] && source /home/${RUID}/.config/user-dirs.dirs
        [ -z $XDG_DESKTOP_DIR ] && XDG_DESKTOP_DIR="/home/${RUID}/Desktop"        
        [ -f /home/${RUID}/.hamonikr/set-user-env.done ] && rm -f /home/${RUID}/.hamonikr/set-user-env.done
        [ -f /home/${RUID}/.hamonikr/backup_user_env.dconf ] && rm -f /home/${RUID}/.hamonikr/backup_user_env.dconf
        [ -f /home/${RUID}/.hamonikr/set-user-env.log ] && rm -f /home/${RUID}/.hamonikr/set-user-env.log
        [ -f $XDG_DESKTOP_DIR/hamonikr-community.desktop ] && rm -f $XDG_DESKTOP_DIR/hamonikr-community.desktop

        ;;
    failed-upgrade)
        ;;
    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

