#!/bin/bash

# ui 파일에서 ui.h 파일 생성
intltool-extract --type=gettext/glade *.ui

# xgettext를 사용하여 Python 소스 파일에서 문자열을 추출하고 임시 .pot 파일 생성
# xgettext -o video2gif.pot -L Glade video2gif.ui
xgettext --language=Python --keyword=_ --keyword=N_ --output=video2gif.pot *.py *.ui.h

# msginit을 사용하여 최종 .po 파일 생성
# msginit --no-translator --input=video2gif.pot --locale=ko_KR --output-file=locale/ko/LC_MESSAGES/video2gif.po

# 새로 추가된 번역 텍스트를 기존의 번역파일에 병합
msgmerge -U locale/ko/LC_MESSAGES/video2gif.po video2gif.pot

# 임시 파일 정리
# rm -f messages.pot *.ui.h
rm -f *.ui.h
