name: Build

on:
  push:
    tags:
      - "v*"

jobs:
  build-ubuntu-2404:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Build Debian Package
        uses: jtdor/build-deb-action@v1
        env:
          DEB_BUILD_OPTIONS: noautodbgsym
        with:
          docker-image: ubuntu:24.04
          buildpackage-opts: -us -uc
          before-build-hook: apt-get install -y devscripts equivs && mk-build-deps --install --remove debian/control && debchange --controlmaint --local="+ci${{ github.run_id }}~ubuntu2404~git$(git rev-parse --short HEAD)" "CI build"
          extra-build-deps: devscripts git equivs debhelper build-essential
          host-arch: amd64
          artifacts-dir: debian/artifacts-ubuntu2404

      - name: Upload Debian Package
        uses: actions/upload-artifact@v2
        with:
          name: debian-package-ubuntu2404
          path: debian/artifacts-ubuntu2404/*.deb

  build-ubuntu-2204:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Build Debian Package
        uses: jtdor/build-deb-action@v1
        env:
          DEB_BUILD_OPTIONS: noautodbgsym
        with:
          docker-image: ubuntu:22.04
          buildpackage-opts: -us -uc
          before-build-hook: apt-get install -y devscripts equivs && mk-build-deps --install --remove debian/control && debchange --controlmaint --local="+ci${{ github.run_id }}~ubuntu2204~git$(git rev-parse --short HEAD)" "CI build"
          extra-build-deps: devscripts git equivs debhelper build-essential
          host-arch: amd64
          artifacts-dir: debian/artifacts-ubuntu2204

      - name: Upload Debian Package
        uses: actions/upload-artifact@v2
        with:
          name: debian-package-ubuntu2204
          path: debian/artifacts-ubuntu2204/*.deb

  generate-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          includeInvalidCommits: true
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}

      - name: Release Changelog Builder
        id: release_changelog      
        uses: mikepenz/release-changelog-builder-action@v5
        with:
          configurationJson: |
            {
              "template": "#{{CHANGELOG}}\n\n<details>\n<summary>Uncategorized</summary>\n\n#{{UNCATEGORIZED}}\n</details>",
              "categories": [
                {
                    "title": "## 💬 Other",
                    "labels": ["other"]
                },
                {
                    "title": "## 📦 Dependencies",
                    "labels": ["dependencies"]
                }
              ]
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    needs: [build-ubuntu-2404, build-ubuntu-2204, generate-changelog]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Download build artifacts for Ubuntu 24.04
        uses: actions/download-artifact@v2
        with:
          name: debian-package-ubuntu2404
          path: .

      - name: Download build artifacts for Ubuntu 22.04
        uses: actions/download-artifact@v2
        with:
          name: debian-package-ubuntu2204
          path: .

      - run: ls -R .

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: ./*.deb
          body: ${{ steps.changelog.outputs.changelog }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
